# Generated by Django 4.0.4 on 2022-04-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queijaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='leite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producao',
            name='lote',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producao',
            name='observacao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='peso',
            field=models.FloatField(),
        ),
    ]
