# Generated by Django 4.0.4 on 2022-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queijaria', '0002_alter_producao_leite_alter_producao_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producao',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
