# Generated by Django 4.0.4 on 2022-04-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queijaria', '0002_fornecedor_recebimentoleite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentoleite',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
    ]
