# Generated by Django 4.0.4 on 2022-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queijaria', '0003_alter_producao_observacao_alter_producao_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='acucar',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producao',
            name='peso',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producao',
            name='rendimento',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producao',
            name='sal',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
