# Generated by Django 4.0.4 on 2022-05-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queijaria', '0004_alter_producao_acucar_alter_producao_peso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='producao',
            options={'default_related_name': 'producao'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'default_related_name': 'produto'},
        ),
        migrations.AddField(
            model_name='produto',
            name='codBarras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='produto',
            name='valorCompra',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='valorVenda',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('unidade', models.CharField(max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='queijaria.produto')),
            ],
        ),
    ]
