# Generated by Django 4.0.4 on 2022-04-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queijaria', '0004_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
