# Generated by Django 4.0.4 on 2022-05-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('queijaria', '0009_alter_estoque_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('nascimento', models.DateField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('inscricao_estadual', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'pessoajuridica'), ('model', 'PessoaJuridica')), models.Q(('app_label', 'pessoafisica'), ('model', 'PessoaFisica')), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
        ),
    ]
