# Generated by Django 4.0.4 on 2022-05-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queijaria', '0025_itemvenda_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(default='Pago', max_length=20),
        ),
    ]
